version: 0.1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
on_success:
- cmd: >-
    cd "%APPVEYOR_BUILD_FOLDER%"

    move preloader dist

    move lib\BepInEx dist\BepInEx\core

    md dist\BepInEx\plugins\HunieMod

    move bin\%CONFIGURATION%\* dist\BepInEx\plugins\HunieMod

    move LICENSE.txt dist\HunieMod_License.txt

    move README.md dist\HunieMod_Readme.txt

    7z a "HunieMod_%APPVEYOR_BUILD_VERSION%.zip" .\dist\*

    appveyor PushArtifact "HunieMod_%APPVEYOR_BUILD_VERSION%.zip"